--create inpFunc
inpFunc a b = [a..b] 

applicatorFunc inpFunc a b s 
    | s == 'c'  = sum (inpFunc a b)  -- Calculate the sum of numbers generated by inpFunc
    | otherwise = sum (inpFunc a b) / 5  -- Calculate the average of numbers generated by inpFunc


main = do
    let result = applicatorFunc inpFunc 1 5  's'-- Call applicatorFunc with inpFunc and 's' as args
    putStrLn ("sum = " ++ show result)